name: Auto-deploy to Heroku

on: push

jobs:
  deploy-to-production:
    name: Deploy next to markdown-demo
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/next'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'markdown-demo'
          dontautocreate: true
